{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.15.0.aar",
          "url": "bgeo-android-0.15.0.aar",
          "size": 355017,
          "sha512": "17cff12445798acfa094807bfe08c33ba8e7a06c2b4ff99a782a2c7751cc70d698b49f5af47de262bfa4326a461172ab4ee0a109b891bd0420b5c48b3d74ca2d",
          "sha256": "979f489e05c34e435153c81694014c2218f0d9502f906bbc83459cf9e6b2e9bb",
          "sha1": "b5b880461ba5fab2a2906965049edaf0b08bff82",
          "md5": "4a5dfd22cdc50e2b1b0f25b6bd416138"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.15.0.aar",
          "url": "bgeo-android-0.15.0.aar",
          "size": 355017,
          "sha512": "17cff12445798acfa094807bfe08c33ba8e7a06c2b4ff99a782a2c7751cc70d698b49f5af47de262bfa4326a461172ab4ee0a109b891bd0420b5c48b3d74ca2d",
          "sha256": "979f489e05c34e435153c81694014c2218f0d9502f906bbc83459cf9e6b2e9bb",
          "sha1": "b5b880461ba5fab2a2906965049edaf0b08bff82",
          "md5": "4a5dfd22cdc50e2b1b0f25b6bd416138"
        }
      ]
    }
  ]
}
