{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.15.0.aar",
          "url": "bgeo-android-0.15.0.aar",
          "size": 355018,
          "sha512": "c1bcadceb4888afd8211b30adfbfe46933845c0ef1072d660c6eaec5f49b98259fa041415ba0304c95d87eaddaa7c15983f7808f5ae4ce0bccd446b68ede7ca9",
          "sha256": "0f04cd6927f613d7387f8751166b32dbcdb20fb698cefe5883106692a1605428",
          "sha1": "a490f7d3b2c6bb4c3352686809b8e37c610ce430",
          "md5": "c5f7841c2c6572051b60bca8a84e7f8f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.15.0.aar",
          "url": "bgeo-android-0.15.0.aar",
          "size": 355018,
          "sha512": "c1bcadceb4888afd8211b30adfbfe46933845c0ef1072d660c6eaec5f49b98259fa041415ba0304c95d87eaddaa7c15983f7808f5ae4ce0bccd446b68ede7ca9",
          "sha256": "0f04cd6927f613d7387f8751166b32dbcdb20fb698cefe5883106692a1605428",
          "sha1": "a490f7d3b2c6bb4c3352686809b8e37c610ce430",
          "md5": "c5f7841c2c6572051b60bca8a84e7f8f"
        }
      ]
    }
  ]
}
