{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.15.0.aar",
          "url": "bgeo-android-0.15.0.aar",
          "size": 343477,
          "sha512": "d81a2b3488f347e792b3359ae96a1b8a76b55585524655beaa92e5969fa0bdf4308e4980db123b555bb755f2306d979cd2f8eb8223dc627c9e749170b8714b86",
          "sha256": "cfc78efa6fb0c34c408b8eb86ec369e30a95d1f1dd1202f85977ea0e258be8d4",
          "sha1": "8ab69b7e50e7df17b962a1e266498fd1d319c742",
          "md5": "790bdb80ede04641b218719ea37b03b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.15.0.aar",
          "url": "bgeo-android-0.15.0.aar",
          "size": 343477,
          "sha512": "d81a2b3488f347e792b3359ae96a1b8a76b55585524655beaa92e5969fa0bdf4308e4980db123b555bb755f2306d979cd2f8eb8223dc627c9e749170b8714b86",
          "sha256": "cfc78efa6fb0c34c408b8eb86ec369e30a95d1f1dd1202f85977ea0e258be8d4",
          "sha1": "8ab69b7e50e7df17b962a1e266498fd1d319c742",
          "md5": "790bdb80ede04641b218719ea37b03b2"
        }
      ]
    }
  ]
}
