{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.16.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.16.8.aar",
          "url": "bgeo-android-0.16.8.aar",
          "size": 367308,
          "sha512": "fd69f10ecde399151e4bb19a07f33b97bbef020ffbc691cad0e4e6fb4fd5af1b271d8ed868493d61aa5061ef011bfd9f751c5f29300666856fa6eda6a7da894c",
          "sha256": "9ae972d11ed96eaf0d6803e82e502ba4d1746a2731e3853553323a0aaa9be570",
          "sha1": "9abe77a04a978f41ebe33ad187413c5d39d06eea",
          "md5": "520052fe68086485acb946f7d5afb7b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.16.8.aar",
          "url": "bgeo-android-0.16.8.aar",
          "size": 367308,
          "sha512": "fd69f10ecde399151e4bb19a07f33b97bbef020ffbc691cad0e4e6fb4fd5af1b271d8ed868493d61aa5061ef011bfd9f751c5f29300666856fa6eda6a7da894c",
          "sha256": "9ae972d11ed96eaf0d6803e82e502ba4d1746a2731e3853553323a0aaa9be570",
          "sha1": "9abe77a04a978f41ebe33ad187413c5d39d06eea",
          "md5": "520052fe68086485acb946f7d5afb7b3"
        }
      ]
    }
  ]
}
