{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.14.1.aar",
          "url": "bgeo-android-0.14.1.aar",
          "size": 323776,
          "sha512": "2c9c63ea7d0ca01de55c34d2fa3994282095a252ae79013505f62de3feae3078d736b38a5d9c9e8f6b4b298ecaa155439de7621236b431c9f95b53c02c642f7d",
          "sha256": "e0837d18ccfd04d76a0380f3cb528bc1c7eb8b9b5a069eb294674f59b20c8f56",
          "sha1": "33c5b8ece7162dfae4a40b42de506438cf2b3ac4",
          "md5": "20a9f89991139efcef81deda21f0725a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.14.1.aar",
          "url": "bgeo-android-0.14.1.aar",
          "size": 323776,
          "sha512": "2c9c63ea7d0ca01de55c34d2fa3994282095a252ae79013505f62de3feae3078d736b38a5d9c9e8f6b4b298ecaa155439de7621236b431c9f95b53c02c642f7d",
          "sha256": "e0837d18ccfd04d76a0380f3cb528bc1c7eb8b9b5a069eb294674f59b20c8f56",
          "sha1": "33c5b8ece7162dfae4a40b42de506438cf2b3ac4",
          "md5": "20a9f89991139efcef81deda21f0725a"
        }
      ]
    }
  ]
}
